<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Matraca.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.39.0" />
    <PackageReference Include="Whisper.net" Version="1.9.1" />
  </ItemGroup>

</Project>
