// Generated by node Matraca.Web/export-design.cjs. DS 1.1.0.
namespace Matraca;

internal static class WindowsPanelColors
{
    internal const uint Light = 0xfdfcfb;
    internal const uint Dark = 0x171411;
}
