// DS 1.0.1: the versioned JSON is the only source of design values.
const fs = require('node:fs');
const path = require('node:path');
const tokens = JSON.parse(fs.readFileSync(path.join(__dirname, '../design/docs/design-system-tokens.json'), 'utf8'));
const block = (selector, values) => `${selector} {\n${Object.entries(values).map(([key, value]) => `  ${key}: ${value};`).join('\n')}\n}\n`;
const type = Object.fromEntries(Object.entries(tokens.typeScalePx).map(([key, value]) => [`--type-${key}`, `${value}px`]));
const css = `/* Generated by node Matraca.Web/export-design.cjs. DS ${tokens.version}. */\n`
  + block(':root', { ...tokens.font, ...tokens.geometry, ...type, ...tokens.motion, ...tokens.overlay, '--palette-hue': tokens.families[0].hue, 'color-scheme': 'light', ...tokens.light })
  + tokens.families.map(family => block(`:root[data-palette="${family.id}"]`, { '--palette-hue': family.hue })).join('')
  + block(':root[data-theme="dark"]', { 'color-scheme': 'dark', ...tokens.dark })
  + `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme])', { 'color-scheme': 'dark', ...tokens.dark })}}\n`;
const destination = path.join(__dirname, 'wwwroot/design-tokens.css');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8').replace(/\r\n/g, '\n') !== css) {
    console.error('Production tokens differ from the design source. Run node Matraca.Web/export-design.cjs.');
    process.exitCode = 1;
  } else console.log(`Production tokens match DS ${tokens.version}.`);
} else fs.writeFileSync(destination, css);
