// DS 1.0.1: the versioned JSON is the only source of design values.
const fs = require('node:fs');
const path = require('node:path');
const tokens = JSON.parse(fs.readFileSync(path.join(__dirname, '../design/docs/design-system-tokens.json'), 'utf8'));
const block = (selector, values) => `${selector} {\n${Object.entries(values).map(([key, value]) => `  ${key}: ${value};`).join('\n')}\n}\n`;
const type = Object.fromEntries(Object.entries(tokens.typeScalePx).map(([key, value]) => [`--type-${key}`, `${value}px`]));
const css = `/* Generated by node Matraca.Web/export-design.cjs. DS ${tokens.version}. */\n`
  + block(':root', { ...tokens.font, ...tokens.geometry, ...type, ...tokens.motion, ...tokens.overlay, '--palette-hue': tokens.families[0].hue, 'color-scheme': 'light', ...tokens.light })
  + tokens.families.map(family => block(`:root[data-palette="${family.id}"]`, { '--palette-hue': family.hue })).join('')
  + block(':root[data-theme="dark"]', { 'color-scheme': 'dark', ...tokens.dark })
  + `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme])', { 'color-scheme': 'dark', ...tokens.dark })}}\n`;
// CSS Color 4 OKLCH -> sRGB, quantized to Win32 COLORREF (0x00BBGGRR).
function colorref(value) {
  const match = /^oklch\(([\d.]+)% ([\d.]+) ([\d.]+)\)$/.exec(value);
  if (!match) throw new Error(`Unsupported native color: ${value}`);
  const [, lightness, chroma, hue] = match.map(Number);
  const l = lightness / 100, a = chroma * Math.cos(hue * Math.PI / 180), b = chroma * Math.sin(hue * Math.PI / 180);
  const L = (l + .3963377774 * a + .2158037573 * b) ** 3;
  const M = (l - .1055613458 * a - .0638541728 * b) ** 3;
  const S = (l - .0894841775 * a - 1.291485548 * b) ** 3;
  const channels = [4.0767416621 * L - 3.3077115913 * M + .2309699292 * S,
    -1.2684380046 * L + 2.6097574011 * M - .3413193965 * S,
    -.0041960863 * L - .7034186147 * M + 1.707614701 * S]
    .map(c => Math.round(255 * Math.max(0, Math.min(1, c <= .0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - .055))));
  return `0x${(channels[0] | channels[1] << 8 | channels[2] << 16).toString(16).padStart(6, '0')}`;
}
const native = `// Generated by node Matraca.Web/export-design.cjs. DS ${tokens.version}.\nnamespace Matraca;\n\ninternal static class WindowsPanelColors\n{\n    internal const uint Light = ${colorref(tokens.light['--bg'])};\n    internal const uint Dark = ${colorref(tokens.dark['--bg'])};\n}\n`;
for (const [destination, content] of [
  [path.join(__dirname, 'wwwroot/design-tokens.css'), css],
  [path.join(__dirname, '../Matraca.Windows/WindowsPanelColors.cs'), native],
]) {
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8').replace(/\r\n/g, '\n') !== content) {
      console.error(`Production tokens differ: ${destination}. Run node Matraca.Web/export-design.cjs.`);
      process.exitCode = 1;
    } else console.log(`Production tokens match DS ${tokens.version}: ${destination}`);
  } else fs.writeFileSync(destination, content);
}
